version: '3.3'

services:
  postgresdb:
    container_name: deposito-postgres
    image: 'postgres:15-alpine'
    ports:
      - "5435:5432"
    healthcheck:
      test: ['CMD', 'pg_isready', '-U', 'postgres']
    volumes:
      - 'postgresdb-volume:/var/lib/postgresql/data'
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

volumes:
  postgresdb-volume: