spring:
  application:
    name: Deposito Application
  datasource:
    url: jdbc:postgresql://localhost:5435/deposito_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
    hikari:
      jdbc-url: jdbc:postgresql://localhost:5435/deposito_db
      username: postgres
      password: postgres
      driver-class-name: org.postgresql.Driver
#  jpa:
#    hibernate:
#      ddl-auto: create-drop
  flyway:
    baseline-on-migrate: true
server:
  port: 8089