spring:
  application:
    name: Deposito Application
  datasource:
    url: jdbc:postgresql://localhost:5435/deposito_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
    hikari:
      jdbc-url: jdbc:postgresql://localhost:5435/deposito_db
      username: postgres
      password: postgres
      driver-class-name: org.postgresql.Driver
#  jpa:
#    hibernate:
#      ddl-auto: create-drop
  flyway:
    baseline-on-migrate: true
  kafka:
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      group-id: depositoGroup
    bootstrap-servers: localhost:9092


server:
  port: 8089